# Generated by Django 4.1.7 on 2023-12-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUserx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_id', models.CharField(max_length=250)),
                ('project_id', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
                ('user_agent', models.CharField(max_length=250)),
                ('installed_at', models.DateTimeField()),
                ('uninstalled_at', models.DateTimeField()),
                ('lastseen_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'userx',
            },
        ),
    ]
