# Generated by Django 4.1.7 on 2023-12-25 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeluserx',
            name='installed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modeluserx',
            name='lastseen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modeluserx',
            name='uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
